### ISSUE TITLE
Issue at step 6 in open challenge

### ISSUE THREAD

**Issue by Jhanvi12** [ACM-IGDTUW/Open-Source-Challenge#32]
I am stuck at step 6, last command ! Can u pls help
![image](https://user-images.githubusercontent.com/36741795/79201400-a7c13b00-7e55-11ea-8c09-02b5a8144d21.png)

**Comment by lisa761** [comment]
Hi @Jhanvi12 This is because you have added the wrong origin like I mentioned in this [comment](https://github.com/ACM-IGDTUW/Open-Source-Challenge/issues/11#issuecomment-612800298). You can solve that problem by running:
If you have already forked the repo, you can just run this:
```sh
git remote set-url origin https://github.com/Jhanvi12/Open-Source-Challenge.git
```
If you have not forked the repo, please do that first to move ahead. Once you are done with this, you will also have to update the screenshot of `git remote -v` in Task-1 as it is currently incorrect.

**Comment by Jhanvi12** [comment]
Actually , I have already edited the same post, updated the screenshots also! kindly take a look

**Comment by Jhanvi12** [comment]
@lisa761 please take a look , https://github.com/ACM-IGDTUW/Open-Source-Challenge/issues/11#issuecomment-612799407

**Comment by lisa761** [comment]
Hi, it seems you have made the relevant changes, however your screenshot still has the same link for origin and upstream. See the origin should be `https://github.com/Jhanvi12/Open-Source-Challenge.git` but yours is `https://github.com/ACM-IGDTUW/Open-Source-Challenge.git`. You probably just have to update only the ss.

**Comment by lisa761** [comment]
Closing this  issue since Jhanvi has updated her remotes, just the ss remains.
