### ISSUE TITLE
command showing merge conflicts 

### ISSUE THREAD

**Issue by mishra-shruti96** [ACM-IGDTUW/Open-Source-Challenge#56]
![image](https://user-images.githubusercontent.com/50775636/79308275-ecaca680-7f15-11ea-94a3-668dabf0c262.png)

Please help me in resolving this...

**Comment by sunitijain111** [comment]
command should be **git checkout -b brachname**,  not git chekout branchname

**Comment by lisa761** [comment]
Hi @mishra-shruti96, please do not update your fork using commands other than whats been mentioned in the task. The task asks you to run `git fetch upstream` and _not_ `git pull`. Did you manage to rebase? And yes that's what the command is, and that's what written in the Task as well :)

<img width="960" alt="2020-04-15 (1)" src="https://user-images.githubusercontent.com/52909743/79309766-75c4dd00-7f18-11ea-805f-226a10d70647.png">

Please follow the commands written in the tasks step by step, otherwise we wouldn't be able to help you out. Having merge conflicts can get really messy so lets avoid doing that.

**Comment by lisa761** [comment]
Your merge conflicts are arising because like it says `your branch and origin master have diverged`. This maybe due to some commits or rebase that you have done on your own. You might have to completely reset your master using upstream to over come that. Please follow [this](https://stackoverflow.com/a/42332860/11943496) step by step to do that. Do not add any commands on your own and you shall be fine. If you have forgotten your previous branch name to checkout to that branch, please run `git branch` to view all your branches.

**Comment by mishra-shruti96** [comment]
> Your merge conflicts are arising because like it says `your branch and origin master have diverged`. This maybe due to some commits or rebase that you have done on your own. You might have to completely reset your master using upstream to over come that. Please follow [this](https://stackoverflow.com/a/42332860/11943496) step by step to do that. Do not add any commands on your own and you shall be fine. If you have forgotten your previous branch name, to checkout to that branch, please run `git branch` to view all your branches.

Thank you @lisa761

**Comment by mishra-shruti96** [comment]
> Your merge conflicts are arising because like it says `your branch and origin master have diverged`. This maybe due to some commits or rebase that you have done on your own. You might have to completely reset your master using upstream to over come that. Please follow [this](https://stackoverflow.com/a/42332860/11943496) step by step to do that. Do not add any commands on your own and you shall be fine. If you have forgotten your previous branch name, to checkout to that branch, please run `git branch` to view all your branches.

@lisa761 So firstly i have to reset master using the steps that you have provided and then i can start performing task 3...?

**Comment by lisa761** [comment]
Yes, if you run into any errors, please tell us. Make sure to perform task - 2 before starting on 3.

**Comment by mishra-shruti96** [comment]
> Yes, if you run into any errors, please tell us. Make sure to perform task - 2 before starting on 3.

![image](https://user-images.githubusercontent.com/50775636/79323977-8b440200-7f2c-11ea-86e6-18252a8f2186.png)

yes i have completed task 2 yesterday itself and now this are results i am getting ... please have a look ..

**Comment by lisa761** [comment]
Yes, that's correct. You can start working on 3 now.

**Comment by mishra-shruti96** [comment]
![image](https://user-images.githubusercontent.com/50775636/79324738-b1b66d00-7f2d-11ea-9e86-746a1a10ddc0.png)

@lisa761 sorry to bother you again..but in this step do we have to delete the branch we created yesterday. In my case i created mishra-shruti96-task2 ..so i need to delete this branch right ?

**Comment by lisa761** [comment]
Closing this. Fell free to re-open in case you need to add something.
